apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxy-app
---
apiVersion: v1
kind: Service
metadata:
  name: auth-proxy
  labels:
    app: proxy-app
spec:
  ports:
  - name: http
    port: 8888
    targetPort: 5000
  selector:
    app: proxy-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-auth-proxy
spec:
  selector:
    matchLabels:
      app: proxy-app
  replicas: 2
  template:
    metadata:
      labels:
        app: proxy-app
    spec:
      serviceAccountName: proxy-app
      containers:
      - name: service
        image: alexmilowski/k8s-auth:0016
        args: [ "$(CLIENT_ID)", "$(CLIENT_SECRET)", "--endpoint", "$(ENDPOINT)", "--whitelist", "/conf/whitelist.json", "--session-key", "$(SESSION_KEY)","--session-redis","redis-master.$(MY_NAMESPACE).svc:6379"]
        resources:
          limits:
            cpu: 0.5
            memory: 1Gi
        ports:
        - name: http
          containerPort: 5000
        env:
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: auth-proxy-secret
              key: client-id
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-proxy-secret
              key: client-secret
        - name: SESSION_KEY
          valueFrom:
            secretKeyRef:
              name: auth-proxy-secret
              key: session-key
        - name: ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: auth-proxy-config
              key: endpoint
        volumeMounts:
        - mountPath: /conf
          name: config
      volumes:
        - name: config
          # Omit if you aren't using a whitelist
          configMap:
            name: auth-proxy-whitelist
            items:
            - key: whitelist
              path: whitelist.json
